# Generated by Django 6.0 on 2025-12-18 21:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actualite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('contenu', models.TextField()),
                ('resume', models.TextField()),
                ('image', models.ImageField(upload_to='actu')),
                ('categorie', models.CharField(choices=[('Événement', 'Événement'), ('Annonce', 'Annonce'), ('Travaux', 'Travaux'), ('Culture', 'Culture'), ('Sport', 'Sport')], default='Annonce', max_length=255)),
                ('publie', models.BooleanField(default=False)),
                ('date_publication', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-date_publication'],
            },
        ),
        migrations.CreateModel(
            name='CategorieService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='icons/')),
                ('ordre', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_mairie', models.CharField(max_length=255)),
                ('adresse', models.CharField(max_length=255)),
                ('telephone', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('horaire', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MessageMairie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('prenom', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=255)),
                ('demande', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=32, verbose_name='Nom de la page')),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, verbose_name='Nom de la section')),
            ],
        ),
        migrations.CreateModel(
            name='SiteVisite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('type_lieu', models.CharField(choices=[('Monument', 'Monument historique'), ('Place', 'Place publique'), ('Parc', 'Parc ou jardin'), ('Marché', 'Marché'), ('Édifice', 'Édifice religieux'), ('Site naturel', 'Site naturel'), ('Infrastructure', 'Infrastructure publique'), ('Autre', 'Autre lieu')], default='Autres', max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='ville')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='ville')),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='ville')),
                ('adresse', models.CharField(max_length=255)),
                ('histoire', models.TextField()),
                ('presentation', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PageSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordre', models.PositiveIntegerField(verbose_name='Ordre dans la page')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.page', verbose_name='Page hôte')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.section', verbose_name='Section incluse')),
            ],
            options={
                'ordering': ['ordre'],
                'unique_together': {('page', 'ordre'), ('page', 'section')},
            },
        ),
        migrations.AddField(
            model_name='page',
            name='sections',
            field=models.ManyToManyField(related_name='pages', through='gestion.PageSection', to='gestion.section'),
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('slug', models.SlugField(blank=True, max_length=300, unique=True)),
                ('horaire', models.CharField(blank=True, max_length=255)),
                ('contact', models.CharField(blank=True, max_length=255)),
                ('procedure', models.TextField(blank=True)),
                ('pieces_requises', models.TextField(blank=True)),
                ('conditions', models.TextField(blank=True)),
                ('tarif', models.CharField(blank=True, max_length=255)),
                ('delai', models.CharField(blank=True, max_length=255)),
                ('demande_en_ligne', models.BooleanField(default=False)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='gestion.categorieservice')),
            ],
        ),
        migrations.CreateModel(
            name='DemandeService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_demande', models.CharField(editable=False, max_length=255, unique=True)),
                ('nom', models.CharField(max_length=255)),
                ('prenom', models.CharField(max_length=255)),
                ('telephone', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('statut', models.CharField(choices=[('attente', 'En attente'), ('en_cours', 'En cours'), ('pret', 'Prêt à retirer'), ('retire', 'Retiré'), ('rejete', 'Rejeté')], default='attente', max_length=20)),
                ('date_soumission', models.DateTimeField(auto_now_add=True)),
                ('date_traitement', models.DateTimeField(blank=True, null=True)),
                ('date_retrait', models.DateTimeField(blank=True, null=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion.service')),
            ],
            options={
                'ordering': ['-date_soumission'],
            },
        ),
        migrations.CreateModel(
            name='ChampDemande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_champ', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=200)),
                ('type_champ', models.CharField(choices=[('text', 'Texte court'), ('textarea', 'Texte long'), ('date', 'Date'), ('number', 'Nombre'), ('email', 'Email'), ('tel', 'Téléphone'), ('file', 'Fichier'), ('select', 'Liste déroulante')], max_length=20)),
                ('obligatoire', models.BooleanField(default=True)),
                ('placeholder', models.CharField(blank=True, max_length=200)),
                ('aide', models.CharField(blank=True, max_length=300)),
                ('choix', models.TextField(blank=True)),
                ('ordre', models.IntegerField(default=0)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='champs_requis', to='gestion.service')),
            ],
            options={
                'ordering': ['ordre'],
            },
        ),
    ]
