# Generated by Django 6.0 on 2026-02-02 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_remove_page_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='banner')),
                ('page', models.CharField(max_length=250)),
                ('nom_page', models.CharField(max_length=250)),
                ('titre', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='image')),
                ('titre', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='InfoSiteVisite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modal', models.CharField(max_length=255)),
                ('nom', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Maire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='maire')),
                ('nom', models.CharField(max_length=255)),
                ('localiter', models.CharField(max_length=255)),
                ('eloge', models.CharField(max_length=255)),
                ('presentation', models.TextField()),
                ('diplome', models.CharField(max_length=255)),
                ('icon', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Service_mairie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_service', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('type_service', models.CharField(choices=[('acte naissance', 'Actes Naissance'), ('acte mariage', 'Actes Mariage'), ('acte déces', 'Actes Déces'), ('PACS', 'PACS')], max_length=20)),
                ('descrip', models.CharField(max_length=500)),
                ('lien', models.CharField(max_length=200)),
                ('online', models.CharField(blank=True, max_length=300)),
                ('ordre', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=555)),
                ('lien', models.CharField(max_length=255)),
                ('bouton', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='slider')),
            ],
        ),
        migrations.RemoveField(
            model_name='service',
            name='categorie',
        ),
        migrations.RemoveField(
            model_name='champdemande',
            name='service',
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['ordre', 'nom']},
        ),
        migrations.RenameField(
            model_name='messagemairie',
            old_name='demande',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='contact',
            new_name='demande',
        ),
        migrations.RemoveField(
            model_name='actualite',
            name='publie',
        ),
        migrations.RemoveField(
            model_name='actualite',
            name='resume',
        ),
        migrations.RemoveField(
            model_name='service',
            name='pieces_requises',
        ),
        migrations.RemoveField(
            model_name='service',
            name='procedure',
        ),
        migrations.RemoveField(
            model_name='service',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='sitevisite',
            name='histoire',
        ),
        migrations.RemoveField(
            model_name='sitevisite',
            name='image_2',
        ),
        migrations.RemoveField(
            model_name='sitevisite',
            name='image_3',
        ),
        migrations.AddField(
            model_name='actualite',
            name='lien',
            field=models.CharField(default='lien', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='actualite',
            name='suite',
            field=models.CharField(default='suite', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='icons/'),
        ),
        migrations.AddField(
            model_name='service',
            name='ordre',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='pieces_requises_online',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='service',
            name='pieces_requises_place',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='service',
            name='type_service',
            field=models.CharField(default='TYPE', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sitevisite',
            name='lieu',
            field=models.CharField(default='lieu', max_length=255),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='En_tete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=500)),
                ('sous_titre', models.CharField(blank=True, max_length=500)),
                ('descriprion', models.CharField(max_length=500)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.section')),
            ],
        ),
        migrations.CreateModel(
            name='ModalService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.service')),
            ],
        ),
        migrations.DeleteModel(
            name='CategorieService',
        ),
        migrations.DeleteModel(
            name='ChampDemande',
        ),
    ]
