# Generated by Django 6.0 on 2026-02-03 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_banner_image_infositevisite_maire_service_mairie_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='demandeservice',
            old_name='email',
            new_name='email_demandeur',
        ),
        migrations.RemoveField(
            model_name='demandeservice',
            name='date_traitement',
        ),
        migrations.RemoveField(
            model_name='demandeservice',
            name='telephone',
        ),
        migrations.AddField(
            model_name='demandeservice',
            name='annee_acte',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='demandeservice',
            name='date_deces',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='demandeservice',
            name='date_mariage',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='demandeservice',
            name='date_naissance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='demandeservice',
            name='icon',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='demandeservice',
            name='lien_parente',
            field=models.CharField(blank=True, choices=[('conjoint', 'Conjoint(e)'), ('enfant', 'Enfant'), ('parent', 'Parent'), ('autre', 'Autre')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='demandeservice',
            name='lieu_mariage',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='demandeservice',
            name='lieu_naissance',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='demandeservice',
            name='nom_concerne',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='demandeservice',
            name='nom_defunt',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='demandeservice',
            name='nom_demandeur',
            field=models.CharField(default='nbe', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='demandeservice',
            name='nom_epoux1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='demandeservice',
            name='nom_epoux2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='demandeservice',
            name='nom_mere',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='demandeservice',
            name='nom_pere',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='demandeservice',
            name='nom_service',
            field=models.CharField(choices=[('acte naissance', 'Actes Naissance'), ('acte de mariage', 'Actes Mariage'), ('acte de décès', 'Actes Décès'), ('PACS', 'PACS')], default='naissance', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='demandeservice',
            name='numero_extrait',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='demandeservice',
            name='tel_demandeur',
            field=models.CharField(default='0748971711', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='demandeservice',
            name='nom',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='demandeservice',
            name='prenom',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
