# Generated by Django 6.0 on 2026-02-03 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_rename_email_demandeservice_email_demandeur_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='page_html',
            field=models.CharField(default='nom', max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='banner',
            name='page',
            field=models.CharField(choices=[('accueil', 'Accueil'), ('mairie', 'Mairie'), ('services', 'Services'), ('contact', 'Contact'), ('actualites', 'Actualités')], max_length=50, unique=True),
        ),
    ]
