# Generated by Django 6.0 on 2026-02-03 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_banner_page_html_alter_banner_page'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ModalService',
        ),
    ]
