# Generated by Django 6.0 on 2026-02-03 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_delete_modalservice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demandeservice',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='demandeservice',
            name='nom_service',
        ),
        migrations.AlterField(
            model_name='demandeservice',
            name='lien_parente',
            field=models.CharField(blank=True, default='baby', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.CharField(blank=True, default='baby', max_length=255, null=True),
        ),
    ]
