# Generated by Django 6.0 on 2026-02-04 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0007_remove_demandeservice_icon_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailActualite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('large_description', models.TextField()),
                ('images_actualite', models.ImageField(upload_to='detail_actu')),
                ('alt', models.CharField(blank=True, max_length=255)),
                ('actualite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='gestion.actualite')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pieces_requises_online', models.CharField(blank=True, max_length=255)),
                ('pieces_requises_place', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='InfoSiteVisite',
        ),
        migrations.DeleteModel(
            name='Service_mairie',
        ),
        migrations.RemoveField(
            model_name='service',
            name='pieces_requises_online',
        ),
        migrations.RemoveField(
            model_name='service',
            name='pieces_requises_place',
        ),
        migrations.AlterField(
            model_name='sitevisite',
            name='type_lieu',
            field=models.CharField(choices=[('Monument', 'Monument historique'), ('Place publique', 'Place publique'), ('Parc ou jardin', 'Parc ou jardin'), ('Marché', 'Marché'), ('Édifice religieux', 'Édifice religieux'), ('Site naturel', 'Site naturel'), ('Infrastructure', 'Infrastructure publique'), ('Autre', 'Autre lieu')], default='Autres', max_length=255),
        ),
        migrations.AddField(
            model_name='servicelist',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.service'),
        ),
    ]
