# Generated by Django 6.0 on 2026-02-04 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0008_detailactualite_servicelist_delete_infositevisite_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='adresse',
            new_name='adresse_ville',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='horaire',
            new_name='heure',
        ),
        migrations.AddField(
            model_name='contact',
            name='NB',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='contact',
            name='adresse_postal',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='contact',
            name='heure_samedi',
            field=models.CharField(default='fg', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='jour_samedi',
            field=models.CharField(default='fg', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='jour_semaine',
            field=models.CharField(default='df', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='localisation',
            field=models.CharField(default='df', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True),
        ),
    ]
