# Generated by Django 6.0 on 2026-02-07 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0010_detailactualite_titre_alter_contact_latitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='footer')),
                ('nom_mairie', models.CharField(blank=True, max_length=255, null=True)),
                ('annee_copyright', models.CharField(blank=True, max_length=255, null=True)),
                ('lien_reseau', models.CharField(blank=True, max_length=255, null=True)),
                ('icon_reseau', models.CharField(blank=True, max_length=255, null=True)),
                ('nom_page', models.CharField(max_length=255)),
                ('lien_page', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Histoire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('description1', models.TextField()),
                ('description2', models.TextField()),
                ('description3', models.TextField()),
                ('image', models.ImageField(upload_to='histoire')),
                ('description_bandama', models.TextField()),
                ('titre_video', models.CharField(max_length=255)),
                ('lien_video', models.FileField(upload_to='video_histoire')),
            ],
        ),
        migrations.CreateModel(
            name='Navigation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='navigation')),
                ('nom_mairie', models.CharField(blank=True, max_length=255, null=True)),
                ('slogan', models.CharField(blank=True, max_length=255, null=True)),
                ('lien_page', models.CharField(max_length=255)),
                ('nom_page', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Nombre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_ville', models.CharField(max_length=255)),
                ('nombre_quartiers', models.IntegerField()),
                ('nombre_habitants', models.IntegerField()),
                ('nombre_villages', models.IntegerField()),
                ('nombre_hopitaux', models.IntegerField()),
                ('nombre_ecoles', models.IntegerField()),
                ('nombre_services', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='maire',
            name='eloge',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='maire',
            name='icon',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='maire',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='maire'),
        ),
        migrations.AlterField(
            model_name='maire',
            name='localiter',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='maire',
            name='nom',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
