# Generated by Django 6.0 on 2026-02-07 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0011_footer_histoire_navigation_nombre_alter_maire_eloge_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_page', models.CharField(max_length=255)),
                ('lien_page', models.CharField(max_length=255)),
                ('lien_reseau', models.CharField(blank=True, max_length=255, null=True)),
                ('icon_reseau', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NavigationLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_page', models.CharField(max_length=255)),
                ('lien_page', models.CharField(max_length=255)),
                ('ordre', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='footer',
            name='icon_reseau',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='lien_page',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='lien_reseau',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='nom_page',
        ),
        migrations.RemoveField(
            model_name='navigation',
            name='lien_page',
        ),
        migrations.RemoveField(
            model_name='navigation',
            name='nom_page',
        ),
    ]
