# Generated by Django 6.0 on 2026-02-07 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0012_footerlink_navigationlink_remove_footer_icon_reseau_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footer',
            name='annee_copyright',
            field=models.CharField(default='bb', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='footer',
            name='logo',
            field=models.ImageField(default='bb', upload_to='footer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='footer',
            name='nom_mairie',
            field=models.CharField(default='bb', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='navigation',
            name='logo',
            field=models.ImageField(default='bb', upload_to='navigation'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='navigation',
            name='nom_mairie',
            field=models.CharField(default='bb', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='navigation',
            name='slogan',
            field=models.CharField(default='bb', max_length=255),
            preserve_default=False,
        ),
    ]
