# Generated by Django 6.0 on 2026-02-07 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0013_alter_footer_annee_copyright_alter_footer_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='footerlink',
            name='modal_service',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='footerlink',
            name='nom_service',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
