# Generated by Django 6.0 on 2026-02-10 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0015_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='fonction',
            field=models.CharField(default='Conseiller municipal', max_length=255),
        ),
    ]
