# Generated by Django 6.0 on 2026-02-10 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0016_team_fonction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitevisite',
            name='presentation',
        ),
        migrations.AlterField(
            model_name='sitevisite',
            name='type_lieu',
            field=models.CharField(choices=[('Monument', 'Monument historique'), ('Place publique', 'Place publique'), ('Parc ou jardin', 'Parc ou jardin'), ('Marché', 'Marché'), ('Édifice religieux', 'Édifice religieux'), ('Site naturel', 'Site naturel'), ('Infrastructure', 'Infrastructure publique'), ('Hotel', 'Hôtel'), ('école', 'école')], default='Autres', max_length=255),
        ),
    ]
