# Generated by Django 6.0 on 2026-02-10 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0017_remove_sitevisite_presentation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Legislation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('sous_titre', models.CharField(blank=True, max_length=255)),
                ('icone', models.CharField(max_length=255)),
                ('document', models.FileField(upload_to='legislation')),
            ],
        ),
    ]
