# Generated by Django 6.0 on 2026-02-10 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0018_legislation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legislation',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='legislation'),
        ),
    ]
