# Generated by Django 6.0 on 2026-02-10 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0019_alter_legislation_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='legislation',
            name='document',
        ),
        migrations.CreateModel(
            name='DemandeLegalisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to='demandes/')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('code_suivi', models.CharField(blank=True, max_length=20, unique=True)),
                ('type_legalisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.legislation')),
            ],
        ),
    ]
