# Generated by Django 6.0 on 2026-02-10 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0020_remove_legislation_document_demandelegalisation'),
    ]

    operations = [
        migrations.AddField(
            model_name='footer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='footer_image'),
        ),
    ]
