# Generated by Django 6.0 on 2026-02-10 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0021_footer_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footerlink',
            name='icon_reseau',
            field=models.CharField(blank=True, default='a', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='footerlink',
            name='lien_reseau',
            field=models.CharField(blank=True, default='z', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='footerlink',
            name='modal_service',
            field=models.CharField(blank=True, default='z', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='footerlink',
            name='nom_service',
            field=models.CharField(blank=True, default='z', max_length=255),
            preserve_default=False,
        ),
    ]
