# Generated by Django 6.0 on 2026-02-10 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0023_contact_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='NB',
            field=models.TextField(blank=True),
        ),
    ]
