# Generated by Django 6.0 on 2026-02-11 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0024_alter_contact_nb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maire',
            name='presentation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
