# Generated by Django 6.0 on 2026-02-11 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0025_alter_maire_presentation'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='icon',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='fonction',
            field=models.CharField(blank=True, default='Conseiller municipal', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='team'),
        ),
        migrations.AlterField(
            model_name='team',
            name='nom',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='prenom',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
