# Generated by Django 6.0 on 2026-02-11 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0026_team_icon_alter_team_fonction_alter_team_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actualite',
            name='categorie',
            field=models.CharField(choices=[('Événement', 'Événement'), ('Annonce', 'Annonce'), ('Travaux', 'Travaux'), ('Culture', 'Culture'), ('Sport', 'Sport'), ('Education', 'Education')], default='Annonce', max_length=255),
        ),
    ]
