# Generated by Django 6.0 on 2026-02-11 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0027_alter_actualite_categorie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailactualite',
            name='large_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
