# Generated by Django 6.0 on 2026-02-11 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0028_alter_detailactualite_large_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='titre',
        ),
    ]
