# Generated by Django 6.0 on 2026-02-11 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0029_remove_image_titre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='icon',
            field=models.JSONField(blank=True, max_length=255, null=True),
        ),
    ]
