# Generated by Django 6.0 on 2026-02-11 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0030_alter_team_icon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='en_tete',
            old_name='descriprion',
            new_name='description',
        ),
    ]
