# Generated by Django 6.0 on 2026-02-11 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0031_rename_descriprion_en_tete_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandeservice',
            name='date_retrait',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
