# Generated by Django 6.0 on 2026-02-11 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0032_alter_demandeservice_date_retrait'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='page',
            field=models.CharField(choices=[('accueil', 'Accueil'), ('mairie', 'Mairie'), ('services', 'Services'), ('contact', 'Contact'), ('actualites', 'Actualités'), ('histoire', 'Histoire')], max_length=50, unique=True),
        ),
    ]
