# Generated by Django 6.0 on 2026-02-15 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0033_alter_banner_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandelegalisation',
            name='statut',
            field=models.CharField(choices=[('attente', 'En attente'), ('en_cours', 'En cours'), ('traitee', 'Traité'), ('rejete', 'Rejeté')], default='attente', max_length=20),
        ),
    ]
