# Generated by Django 6.0 on 2026-02-15 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0034_demandelegalisation_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandelegalisation',
            name='statut',
            field=models.CharField(choices=[('attente', 'En attente'), ('en_cours', 'En cours'), ('traitee', 'Traité'), ('rejete', 'Rejeté')], default='En attente', max_length=20),
        ),
    ]
